### ISSUE TITLE
Implement Photo Upload for Posts with Cloudinary Integration

### ISSUE THREAD

**Issue by mojahmed** [Code-the-Dream-School/hh-team2-back#13]
Description
We need to implement the functionality to handle post photo uploads for posts in our application. This involves integrating Cloudinary for image storage and managing image uploads in the Posts Controller, Routes, and Middleware.
Tasks

    #Posts Controller
        Integrate Cloudinary image upload functionality for post images.
        Upon post creation or update, check if an image is provided and upload it to Cloudinary.
        Save the Cloudinary URL in the imageUrl field in the Post model.
        If an image already exists for a post, ensure the old image is deleted from Cloudinary before uploading the new one.

    Post Routes
        Update the post creation and update routes to handle image file uploads.
        Ensure that image files are uploaded to Cloudinary, and the returned URL is saved in the post.
        Add logic to delete the old image from Cloudinary when updating the image for an existing post.

    Middleware
        Implement middleware (using Multer) to handle image file uploads.
        Validate that the uploaded file is an image before uploading to Cloudinary.

Testing

    Create a Post: Test creating a new post with an image attached and verify that the image is uploaded to Cloudinary.
    Update Post: Test updating an existing post's image and ensure the old image is deleted from Cloudinary.
    Verify Post Model: Ensure the imageUrl field correctly stores the URL of the uploaded image.

Please implement the above functionality and test the changes using Postman.

**Comment by tianahR** [comment]
@mojahmed here is the PR related to this issue : https://github.com/Code-the-Dream-School/hh-team2-back/pull/16
